site_name: 'Deberes de Gabriel'
theme:
  name: 'mkdocs'
  custom_dir: 'overrides'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'
extra_css:
  - 'overrides/extra.css'

nav:
  - Inici: index.md
  - Articles EDD:
      - Actividades sobre Ant y Maven:
          - Ant Project: edd/ActividadesAntymaven/ant_project/src/Calculadora.java
          - Maven Project: edd/ActividadesAntymaven/maven_project/src/App.java
      - ActividadesMkdocs:
          - Actividad 1-2 RSC SVN: edd/ActividadesMkdocs/actividad_1_2_RSC_SVN.txt
          - Actividad 3 RSC SVN: edd/ActividadesMkdocs/actividad_3_RSC_SVN.txt
          - Actividad 4 RSC SVN: edd/ActividadesMkdocs/actividad_4_RSC_SVN.txt
      - Artículos UD1:
          - Article 1: edd/ArticulosUD1/article1.md
          - Article 2: edd/ArticulosUD1/article2.md
          - Article 3: edd/ArticulosUD1/article3.md
          - Article 4: edd/ArticulosUD1/article4.md
          - Article 5: edd/ArticulosUD1/article5.md
          - Article 6: edd/ArticulosUD1/article6.md
  - Articles LMI:
      - Artículos:
          - Article 1: lmi/Articulos/article1.md
          - Article 2: lmi/Articulos/article2.md
      - Html:
          - Ejercicio 1: lmi/Html/Ejercicio1.html
          - Ejercicio 2: lmi/Html/Ejercicio2.html
          - Ejercicio 3: lmi/Html/Ejercicio3.html
          - Ejercicio 4: lmi/Html/Ejercicio4.html
          - Ejercicio 5: lmi/Html/Ejercicio5.html
          - Ejercicio 6: lmi/Html/Ejercicio6.html
          - Ejercicio 7': lmi/Html/Ejercicio7.html
          - Ejercicio 8: lmi/Html/Ejercicio8.html
          - Ejercicio 9: lmi/Html/Ejercicio9.html
          - Ejercicio 10: lmi/Html/Ejercicio10.html
          - Ejercicio 11: lmi/Html/Ejercicio11.html
          - Ejercicio 12: lmi/Html/Ejercicio12.html
          - Ejercicio 13: lmi/Html/Ejercicio13.html
          - Ejercicio 14: lmi/Html/Ejercicio14.html
          - Ejercicio 15:  lmi/Html/Ejercicio15.html
          - Formulario: lmi/Html/Formulario.html
      - Javascript:
          - 1. Declaració de variables: lmi/Javascript/1.Declaraciódevariablesioperadorsjavascript.js
          - 2. Ús de typeof: lmi/Javascript/2.Úsdetypeojavascript.js
          - 3. Conversió de tipus automàtica: lmi/Javascript/3.Conversiódetipusautomàticajavascript.js
          - 4. Vectors i accés a elements: lmi/Javascript/4.Vectorsiaccésaelementsjavascript.js
          - 5. JSON bàsic: lmi/Javascript/5.JSONbàsicjavascript.js
          - 6. Condicionals simples: lmi/Javascript/6.Condicionalssimplesamb.js
          - 7. Condicional switch: lmi/Javascript/7.Condicionalswitch.js
          - 8. Bucle for: lmi/Javascript/8.Bucleforjavascript.js
          - 9. Bucle for...of: lmi/Javascript/9.Buclefor...ofivectorsjavascript.js
          - 10. While i do...while: lmi/Javascript/10.Whileidowhilejavascript.js
          - 11. Funció que retorna un valor: lmi/Javascript/11.Funcióqueretornaunvalorjavascript.js
          - 12. Funció amb paràmetres per defecte: lmi/Javascript/12.Funcióambparàmetresperdefectejavascript.js